#!/bin/bash
(cd misc && make fenconv)
fenmoves=/tmp/fenmoves$$
fenmove=/tmp/fenmove$$
simout=/tmp/simout$$
origpgn=/tmp/origpgn$$
gameno=`shuf -i 1-12998 -n 1`
pgn-extract -s --minmoves 4 --selectonly $gameno misc/GriffySr.pgn > $origpgn
pgn-extract --notags -s -Wfen --minmoves 4 --selectonly $gameno misc/GriffySr.pgn | grep -v '^$' > $fenmoves
cat $origpgn
movecount=`wc -l < $fenmoves`
movecount=`expr $movecount - 1`
moveno=`shuf -i 2-$movecount -n 1`
echo 'moveno' $moveno 'gameno' $gameno
tail -n+$moveno < $fenmoves | head -n1 > $fenmove
cat $fenmove
misc/fenconv < $fenmove > amt_board.vh
make amt
./amt > $simout
allmoves="`egrep '^move_index' $simout | awk '{ print $2 }'`"
echo $allmoves
pgn-extract -s -Wuci $origpgn
playedmove=`pgn-extract --notags -s -Wuci $origpgn | grep -v '^$' | cut -d ' ' -f $moveno`
echo played move $playedmove
echo $allmoves | grep -w -q $playedmove
status=$?
if [ $status -eq 0 ]
then
    echo we have that
else
    echo not generated
fi
rm -f $fenmoves $fenmove $simout $origpgn
