#!/bin/bash
xboard -boardSize Medium -fUCI -fcp numbattcp \
       -fd /home/stacey/src/numbat/vivado/comms \
       -scp '/home/stacey/src/phalanx/phalanx -e 20' \
       -sd /home/stacey/src/phalanx/ \
       -saveGameFile /home/stacey/tmp/ph/phgames.pgn
