#!/bin/bash
if [ ! -f ../random_constant.vh ]
then
    printf '%s: this script must be run from numbat/vivado\n' $0 1>&2
    exit 1
fi
seed=`cat ../random_constant.vh | awk ' { print $3 } '`
if [ "$seed" = '' ]
then
    printf '%s: cannot find previous seed\n' $0 1>&2
    exit 1
fi
runno=0
while [ $runno -lt 50 ]
do
    seed=`hexdump -vn4 -e'"%08X" 1 "\n"' /dev/urandom`
    tmppath=~/tmp/timing/run_$seed
    rm -fr $tmppath
    mkdir -p $tmppath
    printf 'Starting run %d\n' $runno
    printf '`define RANDOM_CONSTANT '"'"'h%s\n' $seed > ../random_constant.vh
    (make distclean && make create_hardware) > $tmppath/build.log 2>&1
    cp ./numbat/numbat_1.runs/impl_1/*.rpt $tmppath
    runno=`expr $runno + 1`
done
printf 'Done.\n'
exit 0
    
