#!/bin/bash
(cd .. && make) > /dev/null 2>&1
(cd ../misc && make fenconv) > /dev/null 2>&1
fenmoves=/tmp/fenmoves$$
fenmove=/tmp/fenmove$$
simout=/tmp/simout$$
origpgn=/tmp/origpgn$$
ucitrunc=/tmp/ucitrunc$$
allmoveslist=/tmp/allmoveslist$$
testpgn=/tmp/testpgn$$.pgn
testresult=/tmp/testresult$$
amtdir=/tmp/amt$$
stop=0
counter=0
srclist="`make srclist`"
mkdir -p $amtdir $amtdir/tb
cp $srclist $amtdir
cp amt.sv $amtdir/tb
cp ../attack_mask.vh ../numbat.vh ../mobility*.vh ../evaluate*.vh $amtdir
while [ $stop -eq 0 ]
do
    gameno=`shuf -i 1-12998 -n 1`
    pgn-extract --quiet -s --minmoves 4 --selectonly $gameno ../misc/GriffySr.pgn > $origpgn 2>/dev/null
    pgn-extract --quiet --notags -s -Wfen --minmoves 4 --selectonly $gameno ../misc/GriffySr.pgn 2>/dev/null | grep -v '^$' > $fenmoves
    movecount=`wc -l < $fenmoves`
    movecount=`expr $movecount - 1`
    moveno=`shuf -i 2-$movecount -n 1`
    tail -n+$moveno < $fenmoves | head -n1 > $fenmove
    echo 'moveno' $moveno 'gameno' $gameno `cat $fenmove`
    ../misc/fenconv < $fenmove > $amtdir/amt_board.vh
    (cd $amtdir/tb && iverilog -I.. -g2012 -Wall -o amt amt.sv $srclist > /dev/null 2>&1)
    if [ ! -f $amtdir/tb/amt ]
    then
        echo $0: $amtdir/tb/amt missing 1>&2
        exit 1
    fi
    $amtdir/tb/amt > $simout
    egrep '^move_index' $simout > $allmoveslist
    genmoves=`cat $simout | wc -l`
    allmoves="`cat $allmoveslist | awk '{ print $2 }'`"
    pgn-extract --quiet --notags -s -Wuci $origpgn 2>/dev/null | grep -v '^$' > $ucitrunc
    playedmove=`cat $ucitrunc | cut -d ' ' -f $moveno`
    prevmoveno=`expr $moveno - 1`
    if [ $prevmoveno -lt 1 ]
    then
        echo problem $moveno $prevmoveno
        exit 1
    fi
    prevmoves=`cat $ucitrunc | cut -d ' ' -f 1-$prevmoveno`
    echo $allmoves | grep -w -q $playedmove
    status=$?
    if [ $status -ne 0 ]
    then
        echo played move $playedmove not generated
        exit 1
    fi
    for move in $allmoves
    do
        egrep '^\[' $origpgn > $testpgn
        echo '' >> $testpgn
        echo "$prevmoves" >> $testpgn
        echo $move >> $testpgn
        outcome=`fgrep $move $allmoveslist | awk ' { print $3 } '`
        if [ $outcome = 'B' ]
        then
            echo '1-0' >> $testpgn
        elif [ $outcome = 'W' ]
        then
            echo '0-1' >> $testpgn
        else
            echo '1/2-1/2' >> $testpgn
        fi
        pgn-extract -s --quiet $testpgn >/dev/null 2>$testresult
        fgrep 'Failed to make move' $testresult
        status=$?
        if [ $status -eq 0 ]
        then
            echo illegal move $move found
            cat $testpgn
            cat $testresult
            cat $fenmove
            cat $origpgn
            stop=1
        fi
    done
    counter=`expr $counter + 1`
    if [ $counter -eq 2000 ]
    then
        stop=1
    fi
done
rm -fr $amtdir
rm -f $fenmoves $fenmove $simout $origpgn $ucitrunc $allmoveslist $testpgn $testresult
